
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'opensea_trades'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'opensea_trades'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  opensea_trades:
    # Config indicated by + and applies to all files under models/example/
    erc20:
      +tags: ['sector']
      ethereum:
        +schema: erc20_ethereum
        +materialized: view
    erc721:
      +schema: erc721
      +tags: ['sector']
      ethereum:
        +schema: erc721_ethereum
        +materialized: view
    erc1155:
      +schema: erc1155
      +tags: ['sector']
      ethereum:
        +schema: erc1155_ethereum
        +materialized: view
    opensea:
      +on_schema_change: sync_all_columns
      +materialized: table
      +tags: ['project']
      ethereum:
        +materialized: table
    nft:
      +materialized: table
      +tags: ['sector']
      ethereum:
        +materialized: table
    ens:
      +materialized: table
      +tags: ['project']
      ethereum:
        +materialized: table
    cryptopunks:
      +materialized: table
      +tags: ['project']
      ethereum:
        +materialized: table
